#!/usr/bin/env python3
"""
Main file
"""
import logging
from sqlalchemy import exc as sqlalchemy_exceptions
from auth import Auth

logging.getLogger('sqlalchemy.engine').setLevel(logging.WARNING)

email = 'me@me.com'
password = 'mySecuredPwd'

auth = Auth()

try:
    user = auth.register_user(email, password)
    print("successfully created a new user!")
except ValueError as err:
    print("could not create a new user: {}".format(err))

try:
    user = auth.register_user(email, password)
    print("successfully created a new user!")
except ValueError as err:
    print("could not create a new user: {}".format(err))
